name: flights_with_apm
language: python
variables:
  - name: KAFKA_INPUT_TOPIC_NAME
    inputType: InputTopic
    description: the input kafka topic from which we retrieve the flights points
    defaultValue: live_flights_fuel_estimation
    required: true
  - name: KAFKA_CONSUMER_GROUP
    inputType: FreeText
    description: consummer group to read from the input topic
    defaultValue: live_flights_consumer_fuel_estimation
    required: true
  - name: KAFKA_OUTPUT_TOPIC_NAME
    inputType: OutputTopic
    description: the kafka topic to produce the flights points enriched with with aircraft performances features
    defaultValue: live_flights_with_apm
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
