#!/bin/bash
export KAFKA_BROKER_ADDRESS="localhost:19092"
export KAFKA_INPUT_TOPIC_NAME="historical_flights_fuel_estimation"
export KAFKA_CONSUMER_GROUP="historical_flights_consumer_fuel_estimation"
export KAFKA_OUTPUT_TOPIC_NAME="historical_flights_with_apm"