name: flights_producer
language: python
variables:
  - name: KAFKA_TOPIC
    inputType: OutputTopic
    description: the kafka topic to produce the flights from AviationEdge API
    defaultValue: live_flights_fuel_estimator
    required: true
  - name: LIVE_OR_HISTORICAL
    inputType: FreeText
    description: wether we are in live or historical mode
    defaultValue: live
    required: true
  - name: AVIATION_EDGE_API_KEY
    inputType: Secret
    description: ''
    defaultValue: AVIATION_EDGE_API_KEY
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
