name: flights_producer
language: python
variables:
  - name: KAFKA_TOPIC
    inputType: OutputTopic
    description: the kafka topic to produce the flights from AviationEdge API
    defaultValue: live_flights_fuel_estimator
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
