name: fuel_predictor
language: python
variables:
  - name: KAFKA_TOPIC_NAME
    inputType: InputTopic
    description: ''
    defaultValue: live_flights_with_apm
    required: true
  - name: KAFKA_CONSUMER_GROUP
    inputType: FreeText
    description: ''
    defaultValue: live_flights_with_apm_consumer_primary_keys
    required: true
  - name: LIVE_OR_HISTORICAL
    inputType: FreeText
    description: ''
    defaultValue: live
    required: true
  - name: HOPSWORKS_API_KEY
    inputType: Secret
    description: ''
    defaultValue: HOPSWORKS_API_KEY
    required: true
  - name: HOPSWORKS_PROJECT_NAME
    inputType: FreeText
    description: ''
    defaultValue: Ramane
    required: true
  - name: FEATURE_GROUP_NAME
    inputType: FreeText
    description: ''
    defaultValue: live_flights_tracking_with_apm_data
    required: true
dockerfile: Dockerfile
runEntryPoint: src/restapi.py
defaultFile: src/restapi.py
