name: fuel_predictor
language: python
variables:
  - name: KAFKA_TOPIC_NAME
    inputType: InputTopic
    description: ''
    defaultValue: live_flights_with_apm
    required: true
  - name: KAFKA_CONSUMER_GROUP
    inputType: FreeText
    description: ''
    defaultValue: live_flights_with_apm_consumer_primary_keys
    required: true
  - name: LIVE_OR_HISTORICAL
    inputType: FreeText
    description: ''
    defaultValue: live
    required: true
dockerfile: Dockerfile
runEntryPoint: src/restapi.py
defaultFile: src/restapi.py
