name: Deploy to Quix Cloud Production Environment

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:

  # This workflow contains a single job called "build"
  deploy_to_prod:
    
    #if the pull request is merged and approved, the job will run
    if: ${{ github.event.pull_request.merged == true }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Quix sync
      - name: Quix sync
        run: |
          echo Installing Quix CLI
          curl -fsSL https://github.com/quixio/quix-cli/raw/main/install.sh | bash
          echo Logging into Quix Cloud
          quix login ${{ secrets.QUIX_PAT }}
          quix cloud env sync ${{ secrets.PROD_WORKSPACE_ID }}