# This is a basic workflow to help you get started with Quix CLI and Actions

name: Deploy to Quix Cloud Dev Environment

# Controls when the workflow will run
on:
  # Triggers the workflow when the test.yml workflow is successful
  workflow_run:
    workflows: ["test.yml"]
    types:
      - completed
    branches:
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy_to_dev:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Quix sync
      - name: Quix sync
        run: |
          echo Installing Quix CLI
          curl -fsSL https://github.com/quixio/quix-cli/raw/main/install.sh | bash
          echo Logging into Quix Cloud
          quix login ${{ secrets.QUIX_PAT }}
          quix cloud env sync ${{ secrets.DEV_WORKSPACE_ID }}